.. ###############################################
.. Links
.. ###############################################

.. #### Documentation links
.. _Sphinx: http://www.sphinx-doc.org/en/master/
.. _reStructuredText: http://docutils.sourceforge.net/rst.html
.. _`documentation details concerning ReST`: https://www.sphinx-doc.org/en/master/contents.html
.. _`Matplotlib documentation configuration`: https://matplotlib.org/devel/documenting_mpl.html
.. _api: https://en.wikipedia.org/wiki/Application_programming_interface
.. _`internal references`: https://www.sphinx-doc.org/en/stable/usage/restructuredtext/roles.html
.. _`numpydoc docstring guide`: https://numpydoc.readthedocs.io/en/latest/format.html
.. _Python: http://www.python.org/
.. _`BacterialTyper github`: https://github.com/JFsanchezherrero/BacterialTyper
.. _`PyPI files page`: https://pypi.org/
.. _`pip installing instructions`: https://packaging.python.org/tutorials/installing-packages

.. #### BacterialTyper additional software links
.. _CARD: https://card.mcmaster.ca/
.. _VFDB: http://www.mgc.ac.cn/VFs/
.. _ARIBA: http://sanger-pathogens.github.io/ariba/
.. _PROKKA: https://github.com/tseemann/prokka
.. _SPADES: http://cab.spbu.ru/software/spades/
.. _BUSCO: https://busco.ezlab.org/
.. _KMA: http://www.genomicepidemiology.org/
.. _MULTIQC: https://multiqc.info/
.. _trimmomatic: http://www.usadellab.org/cms/?page=trimmomatic
.. _PhisPy: https://github.com/linsalrob/PhiSpy
.. _NCBI: https://www.ncbi.nlm.nih.gov/
.. _PUBMLST: https://pubmlst.org/
.. _perl: https://perldoc.perl.org/
.. _IslandPath: https://github.com/brinkmanlab/islandpath

.. #### Twitter links
.. _JF: https://twitter.com/JFSanchezBioinf
.. _Cprat: https://twitter.com/crisprat2010

.. #### Sites
.. _IGTP: http://www.germanstrias.org/
.. _HCGB: http://www.germanstrias.org/technology-services/genomica-bioinformatica/
