.. ###############################################
.. Links
.. ###############################################

.. #### Documentation links
.. _Sphinx: http://www.sphinx-doc.org/en/master/
.. _reStructuredText: http://docutils.sourceforge.net/rst.html
.. _`documentation details concerning ReST`: https://www.sphinx-doc.org/en/master/contents.html
.. _`Matplotlib documentation configuration`: https://matplotlib.org/devel/documenting_mpl.html
.. _api: https://en.wikipedia.org/wiki/Application_programming_interface
.. _`internal references`: https://www.sphinx-doc.org/en/stable/usage/restructuredtext/roles.html
.. _`numpydoc docstring guide`: https://numpydoc.readthedocs.io/en/latest/format.html
.. _Python: http://www.python.org/
.. _`BacterialTyper github`: https://github.com/JFsanchezherrero/BacterialTyper
.. _`PyPI files page`: https://pypi.org/
.. _`pip installing instructions`: https://packaging.python.org/tutorials/installing-packages

